### ISSUE TITLE
Report for JUnit4 WebTauRunner just says "Loading Report Data" in some cases

### ISSUE THREAD

**Issue by mattmetlis** [twosigma/webtau#428] opened 2019-08-28 19:11 UTC
I'm using the webtau-junit4 module to use JUnit with `@RunWith(WebTauRunner.class)` and a specified openApiSpecUrl in order to generate a report that includes coverage information for the Open API spec. In some cases the report simply shows
```
WebTau
Loading report data
```
and then never actually loads a report.

I've narrowed it down a bit. This only happens when I am making a REST call in a `@After` annotated method. I can see that `WebTauRunner`'s `afterTestRun` method is called before my test's `@After` annotated method is called. I can make the same exact REST call at the end of my test method instead of in the `@After` annotated method, and then I don't run into this problem.

I'm not yet able to reproduce externally, so I think there's a little more to reproducing it that I can't yet determine.

**Comment by MykolaGolubyev** [comment] 2019-08-29 06:51
It is definitely a bug. I don't think I ever tested using `@After`, only `@Before`. 
Out of curiosity to understand `@After`pattern, what do you run after a test?

**Comment by mattmetlis** [comment] 2019-08-29 11:31
Generally speaking, my REST tests tend to create a bunch of data. I sometimes keep track of what I've created, and have an `@After` method to make sure that test data gets deleted - particularly if the tests are going to be run against a shared environment. I'll sometimes delete the data directly in the test method, but I like to verify it's deleted in an `@After` in case the test fails before the deletion happens.

Any idea where the cause of the problem might be? I've dug through some of the code and so far don't see anything that looks like it could cause this.

**Comment by MykolaGolubyev** [comment] 2019-08-29 11:57
I will try to reproduce it in the near time. No direct ideas at the moment. 
As for the shared data and clean up I feel like we tend not to worry about it at all since we generate new data for each test via ‘post’ and than it stays there. We do have a concept of a lazy resource and I wonder if we should extend its concept to optionally auto clean the resource when all the tests are run.

**Comment by MykolaGolubyev** [comment] 2019-10-16 18:21
should be addressed by #437

**Closed** 2019-10-17 18:43 UTC
Labels: bug
